var talents = {
	"Fast Talk"             : "You are excellent at talking your way out of a tight spot. You may use Wits instead of Empathy when persuading someone of your innocence.",
	"Light Fingered"        : "When executing a particularly delicate bit of pickpocketing, swiping or theft using Pinch, you may Push rolls twice instead of once.{Push2:Pinch}",
	"Stand Firm"            : "When you have time to brace yourself and are hit by something inanimate, you can ignore the first Wound Point you receive. If you receive more than 1 Wound Point in a single hit, reduce the damage by 1.",
	"Bodyguard"             : "If someone in Short range of you is hit in close combat, you can roll Scramble (and Push the roll if you wish) to dive in front of them. One or more successes means you take the hit instead.",
	"Grim Determination"    : "When you clench your jaw and reach deep inside you to succeed against the odds, you can Push rolls based on Strength twice instead of once.{Push2:Strength}",
	"Vital Clue"            : "When you examine an interesting clue about a mystery, situation or threat, you may ask the GM one question about the clue and receive a truthful and useful answer.",
	"Wrack Your Brains"     : "When you are straining your mental faculties to think of a solution or dredge up a memory, you can Push rolls based on Wits twice instead of once.{Push2:Wits}",
	"Poultice & Patience"   : "When you have time to prepare and work carefully, you may fully heal another character, removing either all Wound Points or all Strain Dice. The healing takes at least an hour (GMs discretion) and cannot be used on yourself. It must be done outside combat.",
	"Adept Sawbones"        : "When using Physick to treat a Critical Injury or Panic, you can remove a number of Wound or Strain Points equal to 2 per the number of Successes you roll instead of 1.",
	"I Know A Cove"         : "When you are desperate for help and wrack your brains to think of a solution, you can declare a contact who can help you. The GM must accept the contact, but may determine what they want in return.",
	"Gut Feeling"           : "You have a knack for knowing when trouble is coming. You can roll Notice using Empathy instead of Wits when trying to detect impending problems.",
	"Gone In A Blink"       : "When you're in your element in a chosen urban setting, you may automatically slip away unnoticed if escape is physically possible. The setting must be clear and specific - sewers, crowds, rooftops, backalleys, etc.",
	"Watch The Hands"       : "When you are the centre of attention, you can create a compelling distraction and award an extra fast action, for one round, to an ally of your choice.",
	"Up And At 'Em"         : "You are extremely light on your feet and almost always the first to act. When rolling initiative, roll two dice and use the highest result.",
	"Block Out The Pain"    : "When have to keep going and can't afford to break, you may defer a Critical Injury or Panic roll to the next round. However, when you do roll, you must add a +1 modifier to the result before adding your Wound or Strain Points.",
	"Lucky For You"         : "When you are wounded and roll for a Critical Injury, you may roll twice and choose the result you prefer.",
	"Hold It Together"      : "When your mental strain is becoming too much and you roll on the Panic Table, you may roll twice and choose the result you prefer.",
	"I Saw 'Em Do It"       : "When you are trying to get a glimpse of hidden goings on, you may declare a story detail which might aid you in your efforts. It can be a small to medium inanimate object or a scene feature. The GM may question or tweak your idea and must eventually agree, but may impose consequences on it's use.",
	"Catch The Gist"        : "When you strain to hear a conversation that should be secret, you may roll Notice using Agility instead of Wits.",
	"I Read That Somewhere" : "When you try to make connections between threads about an object, situation or person, you may roll Deduce using Empathy instead of Wits."
}
